
  services:
    postgres:
      image: postgres:15
      container_name: postgres_db_new
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
      container_name: elasticsearch_new
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
      ports:
        - "9200:9200"

    kibana:
      image: docker.elastic.co/kibana/kibana:8.5.0
      container_name: kibana
      depends_on:
        - elasticsearch
      ports:
        - "5601:5601"

  volumes:
    postgres_data:
      driver: local